version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: |
          apt -y update --fix-missing
          apt -y install jq
          pip3 install --user -r requirements.txt
      - run: |
          pip3 install black
          black --check .
      - run: |
          scripts/train.sh
          [ $(jq '.[-1]["main/loss"]' result/log | cut -f 1 -d .) -eq 0 ]
      - run: |
          curl https://sdk.cloud.google.com | bash /dev/stdin --disable-prompts --install-dir /tmp
          export PATH=/tmp/google-cloud-sdk/bin:$PATH

          echo $GCP_KEY_FILE | base64 -d > gcp_key.json

          gcloud config set project $GCP_PROJECT_ID
          gcloud auth activate-service-account --key-file gcp_key.json
          scripts/deploy.sh
