version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: |
          apt -y update --fix-missing
          apt -y install jq
          pip3 install --user -r requirements.txt
      - run: |
          pip3 install black
          black --check .
      - run: |
          scripts/train.sh test/dataset.jl
          jq '.[-1]["main/loss"]' result/log | cut -f 1 -d . | grep '^[0-3]$'
