version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: apt -y update --fix-missing
      - run: apt -y install jq
      - run: pip3 install --user -r requirements.txt
      - run: ./train.py test/dataset.txt
      - run: |
          [ $(jq '.[-1]["main/loss"]' result/log | cut -f 1 -d .) -eq 0 ]
